function robot = cgr_create(theta, d, a, alpha, offset, type, base, ub, lb)
% Create a robot structure

global N_DOFS;

r = struct('base', base, ...
    'theta', theta, ...
    'd', d, ...
    'a', a, ...
    'alpha', alpha, ...
    'offset', offset, ...
    'qc', zeros(N_DOFS, 1), ...
    'type', type, ...
    'jac', zeros(3, N_DOFS), ...
    'T', repmat(zeros(4), 1, 1, N_DOFS), ...
    'ub', ub, ...
    'lb', lb);

robot = r;
end